package com.toolmanagementsystem.demo.enums;


public enum SiteType {
    FAB,
    FABRICATION_PLANT,
    MANUFACTURING_PLANT,
    ASSEMBLY_LINE,
    RESEARCH_AND_DEVELOPMENT,
    DISTRIBUTION_CENTER,
    WAREHOUSE,
    TESTING_LAB,
    DATA_CENTER,
    MAINTENANCE_FACILITY,
    OFFICE_BUILDING,
    LOGISTICS_HUB,
    CLEAN_ROOM,
    PACKAGING_UNIT,
    PROCUREMENT_CENTER,
    TRAINING_CENTER
}
